#!/bin/bash
set -e

PRODUCT=$1
VERSION=$2
ARCH=$3
DISTURL=$4
RELEASES=$5

mkdir -p ${RELEASES} && cd ${RELEASES}

RELEASE=${PRODUCT}-v${VERSION}-${ARCH}

BASE=${PRODUCT}/${ARCH}
FOLDER=${BASE}/${VERSION}

if [ -d "${FOLDER}" ]; then
    echo "${RELEASE} already installed"
    exit 0
fi

curl -s ${DISTURL}/v${VERSION}/${RELEASE}.tar.gz | tar -zx

mkdir -p ${BASE}
mv ${RELEASE} ${FOLDER}

echo "${RELEASE} installed in ${RELEASES}/${FOLDER}"
